### ISSUE TITLE
Read timeout, connectivity problems

### ISSUE THREAD

**Issue by bcambel** [clojurewerkz/cassaforte#100]
Hi @michaelklishin 

Sorry to bother you with an issue, I have two questions and like to hear your suggestions and hopefully merge these suggestions into the documentation. I know that you're extremely busy all of your amazing open-source projects; it would be great if you can help!

1. How to implement proper a read timeout ? Do you suggest to use futures in own clojure code ? 
2. How to implement reconnection policy properly ? 

I'm having serious trouble with Cassandra or with the state of the client, where it seems like all the connections choke up, and the whole system goes down (with 100% CPU usage). Once the processes are started, everything works perfectly fine. Is there any debugging/logging that I can enable, metrics to track ? Any suggestions ? 

It would be super amazing if you take a quick look to my connection settings
https://github.com/bcambel/hackersome/blob/development/src/clj/hsm/system/cassandra.clj#L18

Thanks a lot!
Cheers,
Bahadir

**Comment by arr-ee** [comment]
Functions in `cassaforte.policies` do not mutate connection in any way, they just return policy objects that should be passed to the `connect` function:

```clojure
(cc/connect hosts {:load-balancing-policy (cp/round-robin-policy)
                   :reconnection-policy (cp/exponential-reconnection-policy 100 1000)
                   :retry-policy (cp/retry-policy :fallthrough)}) ;; just an example, not a recommendation 
```

(btw `round-robin` might not be the best idea. More info: http://www.datastax.com/documentation/developer/java-driver/2.1/common/drivers/reference/tuningPolicies_c.html)

**Comment by michaelklishin** [comment]
2. is answered by @arr-ee. 1. should be covered by the Java driver, we should build on top of that. No need to layer future-based timeouts.

Pull requests with new connection options will definitely be considered :)

**Comment by bcambel** [comment]
Thanks @arr-ee 

@michaelklishin it seems like futures are my only option right now :)
