### ISSUE TITLE
Support for non-blocking operations

### ISSUE THREAD

**Issue by Viktor-Kubinec** [clojurewerkz/cassaforte#104]
The current async operations are asynchronous but are still blocking threads.

In here:
https://github.com/clojurewerkz/cassaforte/blob/master/src/clojure/clojurewerkz/cassaforte/client.clj#L274
- calling .getUninterruptibly is blocking the thread. This cause performance problems when using asynchronous frameworks like core.async or vertx. Datastax should support non blocking operations, so it should be possible to register a callback rather than block until the operation is done. I don't know much about Datastax but maybe addListener method available in ResultSetFuture does the job.

**Comment by michaelklishin** [comment]
If you take a closer look you'd see that that call is wrapped in a future and thus only happens when you dereference it. Yes, it's asynchronous programming without the callbacks, available on the JVM since 2004.

**Comment by Viktor-Kubinec** [comment]
There is difference between asynchronous programming and non blocking IO. Asynchronous means that the current thread doesn't get blocked. Non blocking IO doesn't block any thread while waiting for IO. It is nicely explained here http://martintrojer.github.io/clojure/2013/07/07/coreasync-and-blocking-io/

Current Cassaforte async implementation is asynchronous but doesn't leverage the non blocking IO possibilities provided by Datastax. At least that's what is mentioned in their documentation that they support non blocking IO operations.

**Comment by arr-ee** [comment]
@Viktor-Kubinec could you please provide a minimal test case that exposes this problem?

**Comment by Viktor-Kubinec** [comment]
As I said I don't know the API of DataStax that well. I'll look into it and I'll try to come up with something during the weekend.

**Comment by arr-ee** [comment]
I’m sorry for being ambiguous, I meant a testcase that exposes how current implementation of async operations in cassaforte blocks threads (which is something you’re running into, I guess?)

**Comment by michaelklishin** [comment]
@Viktor-Kubinec the calling thread isn't blocked until you dereference the future we return. At the end of the day you have to dereference it at some point to get the data back. It can be a long enough time for it to be fully computed/retrieved in which case it's just a method call. Programming with futures assumes you pass them along until you absolutely must get the value (e.g. to serialise data to send down the wire).

Callbacks is a different story. If you want callbacks, that should be a separate API. Which may have reasons to exist but the claim in the original issue is simply not true.

**Comment by mpenet** [comment]
Currently cassaforte does block a thread from the pool of the driver and also spawns a new one for the future to keep an async feel on cassaforte side. It's fairly inefficient and it's possible to avoid both. 

You can have a look at how it's implemented in https://github.com/mpenet/alia, both async interfaces do not spin a new thread  nor block at any time (no matter the interface used, between core.async or manifold).

**Comment by Viktor-Kubinec** [comment]
Thanks @mpenet, that's exactly what I've been looking for. I have written some tests to show the difference between these two implementations (blocking thread and non blocking thread) when using core async.  I wouldn't say that this test is a proper benchmark. I'm not a performance expert, nor core.async nor cassandra expert. It's just something that I came up with in short time. Test is simply running queries against cassandra for 10 seconds and measuring how many operations it can do in 10 seconds. You can see that for fast queries the performance is comparable. For slower queries the non blocking implementation (alia) is almost 3 times faster than the blocking one (cassaforte). This is caused by blocking the threads by dereferencing the future returned from cassaforte. Alia returns a core.asunc channel which makes it possible to get the query result without blocking any thread while waiting for io. I was running this on my laptop (Ubuntu 14.04, 8 GB Ram, i7 quadcore processor) 

=> (test-d cassa-test-fast-query)
Time's up. Processed so far :  21537
=> (test-d alia-test-fast-query)
Time's up. Processed so far :  23429
=> (test-d cassa-test-slow-query)
Time's up. Processed so far :  1226
=> (test-d alia-test-slow-query)
Time's up. Processed so far :  2831

**Comment by Viktor-Kubinec** [comment]
(ns clj-playground.core
  (:require [qbits.alia :as alia]
            [clojurewerkz.cassaforte.client :as cc]
            [clojure.core.async :as a :refer [>! <! <!! >!! go chan close! go-loop]]))

(def current (atom 0))

(defn is-before [x] (> x (java.lang.System/currentTimeMillis)))

(defn test-d [f]
  (let [c (chan 100)
        end-time (+ 10000 (java.lang.System/currentTimeMillis))]
    (go-loop [x 1] 
             (when (and (>! c (<! (f))) 
                        (< x 50000)
                        (is-before end-time)) 
                   (recur (inc x))))
    (go-loop [y 1]
             (if-let [v (<! c)]
               (if (is-before end-time)
                   (do (swap! current inc)
                       (recur (inc y)))
                   (do (println "Time's up. Processed so far : " @current)
                       (reset! current 0)))))))

(defn cassaforte-execute-chan
  [session query]
  (let [c (chan)]
    (go (>! c (deref (cc/execute-async session query))))
    c))

(def session-cassaforte (cc/connect ["localhost"] {:keyspace "test"}))

(def cluster (alia/cluster {:contact-points ["localhost"]}))
(def session-alia (alia/connect cluster))
(alia/execute session-alia "USE test;")

(def slow-query "select * from test;")
(def fast-query "select * from test where id =767da9c5-7c8e-4bba-ab8d-06c8d5a9d6b0;")
(defn alia-test-slow-query [] (alia/execute-chan session-alia slow-query))
(defn cassa-test-slow-query [] (cassaforte-execute-chan session-alia slow-query))
(defn alia-test-fast-query [] (alia/execute-chan session-alia fast-query))
(defn cassa-test-fast-query [] (cassaforte-execute-chan session-alia fast-query))

**Comment by Viktor-Kubinec** [comment]
The full test code : 
https://github.com/Viktor-Kubinec/playground/blob/master/cassaforte-alia/src/cassaforte-alia/core.clj

**Comment by mpenet** [comment]
:+1: 

That's what I suspected. But t's worth noting that the 2 libraries also differ in other ways (ex: the way the  decoding of the rows is done, support for UDT/tuple etc etc), so it's hard to quantify exactly the impact of my approach.

I have a branch that also allows to have the callback that puts the value in the async chan run in the java-driver IO thread selected instead of a separate thread-pool as it is now, this makes it even faster. I'll see if I can merge that by monday, I want to test it fully before a release.

**Comment by ifesdjeen** [comment]
We have some major upcoming changes to how asyncronous queries are done, just for the reference.

Not sure what's the major difference in decoding rows. We're doing mostly what the Java Driver does under the hood.

**Comment by ifesdjeen** [comment]
New version (now master) allows execution and adding listener. So this one is resolved.
