### ISSUE TITLE
No viable alternative at input ';

### ISSUE THREAD

**Issue by postelrich** [clojurewerkz/cassaforte#106]
I'm trying to do a query using version 2.0.0.  Every query I run using where with vectors instead of a map, 
```
causes SyntaxError line 1:39 no viable alternative at input ';'  com.datastax.driver.core.Responses$Error.asException (Responses.java:95).  
```
Works:
```clojure
(cql/select conn table (query/where {:customer cust :date date}))
```
Doesn't work:
```clojure
(cql/select conn table (query/where
                                      [[= :customer cust]
                                       [> :date start]
                                       [< :date end]]))
```

**Comment by michaelklishin** [comment]
Please post questions to the mailing list.

**Comment by michaelklishin** [comment]
We have some [querying examples](https://github.com/clojurewerkz/cassaforte/blob/master/test/clojurewerkz/cassaforte/cql_test.clj#L145-148) in the test suite.

**Comment by ifesdjeen** [comment]
@postelrich could you please post what's `start` and `end` in that query?

**Comment by postelrich** [comment]
Yes, I just noticed I left in the function vars.

In this case start and end are bigints to store a date.  The column is a bigint type. 

Adding allow-filtering gives me the following error: SyntaxError line 1:140 mismatched character '.' expecting '-'  com.datastax.driver.core.Responses$Error.asException (Responses.java:95)

(cql/select conn "mytable" (query/where [[= :customer "Bob Dole"]
                                       [> :date (bigint 1000)]
                                       [< :date (bigint 1000000)]]
                           (query/allow-filtering true))))

**Comment by ifesdjeen** [comment]
Could you try `long` instead of `bigint`?

**Comment by postelrich** [comment]
The column is a bigint type.  I tried timestamp before.  The query/where doesn't seem to handle the input correctly.  See pic below.

![image](https://cloud.githubusercontent.com/assets/3619876/6787518/bdf4b44a-d169-11e4-9d4c-d15b0dc2dadc.png)

**Comment by michaelklishin** [comment]
What namespace exactly does `query` refer to? What Hayt version is listed in `lein deps :tree`?

**Comment by postelrich** [comment]
Query is [clojurewerkz.cassaforte.query :as query]
grep for hayt found: [cc.qbits/hayt "2.0.0"]

Though with allow-filtering, I get the below. 

![image](https://cloud.githubusercontent.com/assets/3619876/6787565/1801c7ca-d16a-11e4-9158-48c3e00c1330.png)

**Comment by ifesdjeen** [comment]
@postelrich `allow-filtering` shall be outside `where`. 
I get 

```clojure
clojurewerkz.cassaforte.query> (where [[= :customer "Bob Dale"]])
{:where [[#<core$_EQ_ clojure.core$_EQ_@4565a6> :customer "Bob Dale"]]}```

**Comment by postelrich** [comment]
@ifesdjeen ok i see but still if you look at the first image I posted, it comes back with an empty seq.

**Comment by michaelklishin** [comment]
Not for me:

```
user=> (require '[clojurewerkz.cassaforte.query :as q])
nil
user=> (q/where [])
{:where []}
user=> (q/where [[= :name "Cassaforte"]])
{:where [[#<core$_EQ_ clojure.core$_EQ_@21eb6f53> :name "Cassaforte"]]}
user=> (q/where [[= :customer "Bob Dole"]])
{:where [[#<core$_EQ_ clojure.core$_EQ_@21eb6f53> :customer "Bob Dole"]]}
```

**Comment by michaelklishin** [comment]
I highly recommend putting together a failing test case. Really, we can do better than posting screenshots (even on Windows).

**Comment by ifesdjeen** [comment]
@postelrich most likely that's just a dependency issue / conflict. I've tried several versions of Java under several OSes (couldn't test on Windows since I don't have one).

**Comment by postelrich** [comment]
I'm not using windows, just X11 from an ubuntu server.  :)

Dependencies must be off because I compared the source against the repo and its different.  My source is using partition whereas the repo is an alias to hayt.

**Comment by ifesdjeen** [comment]
Ok, that must be the reason then.

**Comment by ifesdjeen** [comment]
@postelrich sorry fonts just looked too much like windows :) you see now how Macs spoil people :D
