### ISSUE TITLE
with-fetch-size doesn't work

### ISSUE THREAD

**Issue by clohfink** [clojurewerkz/cassaforte#107]
The with-fetch-size macro sets *fetch-size* which is never used.  Verified with wireshark that it doesn't affect the page size.

**Comment by michaelklishin** [comment]
@ifesdjeen do we want to re-introduce some more shared state or should we remove that macro?

**Comment by michaelklishin** [comment]
Removed in 7d0b301c365f52c0b292a8671f4f7099dc404750.

**Comment by ifesdjeen** [comment]
Whoopsie, my bad. Fixed: https://github.com/clojurewerkz/cassaforte/commit/8d4f5fa531b203392a79e9937274a8acbca2bf79

**Comment by ifesdjeen** [comment]
Although we _could_ still add macros for all those options, I'm not sure if it's for better or for worse.
