### ISSUE TITLE
Port Cassaforte Query API to new Query Builder

### ISSUE THREAD

**Issue by ifesdjeen** [clojurewerkz/cassaforte#108]

**Comment by michaelklishin** [comment]
I've been following this, great job. Do we plan on replacing Hayt with this? but still keep the API exactly as is?

**Comment by ifesdjeen** [comment]
Yes, that was the idea. I'm trying to stick to Hayt as much as possible, but several things there are bit inconsistent. It will be 99.9% compatible (I'll run it over the Hayt test case when I'm done). For the cases where we decided to take another way, there will be a special namespace "hayt-compatibility" which will live for some time until people migrate.

Some things will be done in a syntax (and naming) introduced by Java Driver, I think that is a better path to follow. Maybe eventually, Hayt will change naming scheme to ones Java Driver introduced, mostly because that's the way people around actually call things.
