### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by denHaag** [clojurewerkz/cassaforte#110]
L.S.,

When I try to connect to Cassadra I get the above message.
Clojure version: 1.6.0
Cassandra 2+
Dependencies in Project.clj file:
:dependencies [[org.clojure/clojure "1.6.0"] [clojurewerkz/cassaforte "2.0.0"]])

What goes wrong?? 
BTW the same error when I try to connect via 'Alia'.

Cheers Johan Tuit,
The Hague
Lower Countries

**Comment by michaelklishin** [comment]
You have [one of the SLF4J](http://stackoverflow.com/questions/7421612/slf4j-failed-to-load-class-org-slf4j-impl-staticloggerbinder) jars missing from your dependencies.
