### ISSUE TITLE
Request and response mismatching after timeouts in 1.2.0

### ISSUE THREAD

**Issue by geodrome** [clojurewerkz/cassaforte#112]
Hello,

I'm on version 1.2.0 and experiencing funny behavior with read queries  via `clojurewerkz.cassaforte.client/execute`. When a query times out and you submit another query shortly after it will return the results for the first query (the one that perviously timed out)! I also found that if I wait 24 seconds between the initial (failed) query and the next query, then all returns to normal and I get the expected result. This seems to happen regardless of the details of the query as I've tested it with a few different queries. Here's how to recreate the issue:

```clj 
(let [try-q (fn [q]
              (try (client/execute q)
                   (catch com.datastax.driver.core.exceptions.NoHostAvailableException e
                     (println "FAILED query: " q))))
      ;; unplug ethernet cable before executing this and plug it back in after it's failed
      a (try-q "SELECT * FROM link_v2 LIMIT 1")
      ;; give yourself time to plug in the ethernet cable, so the next query can succeed
      _ (Thread/sleep 5000) ;; increse to 24000 and the issue goes away
      b (try-q "SELECT * FROM link_v2 LIMIT 2")]
  ;; expected [0 2], got [0 1]
  [(count a) (count b)])
```

I am wondering if there's an issue with the Java driver, cassaforte, or if perhaps I'm doing something wrong. Thank you very much for your help.

**Comment by michaelklishin** [comment]
Request and response matching is performed by the Java driver. I highly recommend trying to reproduce it with the Java client (from Clojure or not).

**Comment by michaelklishin** [comment]
I doubt Java driver used in 1.2.x is getting much attention these days. We also don't have the resources to maintain 1.2.x but if all it takes is bumping a Java driver dependency, for example, we can do a new release.

**Comment by geodrome** [comment]
Thank you for the quick response. I finally got around to investigating this further. I started reproducing the issue with the Java client from Clojure, but found myself copying from the cassaforte code base so I tried something else. I tried nudging the version of `com.datastax.cassandra/cassandra-driver-core` (See: http://mvnrepository.com/artifact/com.datastax.cassandra/cassandra-driver-core) from 1.0.3 all the way to 1.0.8 which failed to compile, I kept nudging it down from there until finally 1.0.5 compiled and seems to have fixed the issue (I failed to reproduce it several times). I ran the tests with 1.0.5 and they all passed, but for one error:

```
lein test :only clojurewerkz.cassaforte.schema-test/create-alter-table-add-column-test

ERROR in (create-alter-table-add-column-test) (InvalidQueryException.java:35)
Uncaught exception, not in assertion.
expected: nil
  actual: com.datastax.driver.core.exceptions.InvalidQueryException: Cannot change title from type timestamp to type varchar: types are incompatible.
 at com.datastax.driver.core.exceptions.InvalidQueryException.copy (InvalidQueryException.java:35)
    com.datastax.driver.core.ResultSetFuture.extractCauseFromExecutionException (ResultSetFuture.java:269)
    com.datastax.driver.core.ResultSetFuture.getUninterruptibly (ResultSetFuture.java:183)
```

This is the extent the full extent of my investigation to date. Not sure when I'll next have a chance to look at this, but just wanted to post the latest I had.

**Comment by michaelklishin** [comment]
`1.2.x` is no longer supported but since all we have to do is bumping Java driver version, we'll do a release. Should we make it depend on `1.0.8`?

**Comment by geodrome** [comment]
I wouldn't feel comfortable with another release just yet. Cassaforte only `com.datastax.cassandra/cassandra-driver-core 1.0.5` compiled and even then there was an error in the tests. So I'd say hold off on another release until I or someone else has had more time examine and test things.

**Comment by michaelklishin** [comment]
I'm afraid the solution to this should be: use more recent versions. We'll be releasing Cassaforte 3.0 based on Java driver 2.x soon, and then jump to Java driver 3.0 in master.
