### ISSUE TITLE
High Garbage Produced by Cassaforte Select

### ISSUE THREAD

**Issue by CodingFabian** [clojurewerkz/cassaforte#113]
I am looking at the garbage created by our clojure component, which uses cassaforte 2.0.0 to load data.
The following screenshot is from jprofiler, which shows a lot of temporary java.lang.Method allocations by cassaforte.
![screen shot 2015-08-03 at 13 25 12](https://cloud.githubusercontent.com/assets/176132/9036609/5ad1dca2-39e3-11e5-88d9-e1a3158ff4d4.png)

For me it seems like the deserialisation does introspection on every query result.
i am not familiar with the inner workings about clojure, but I wonder if this can be optimized in a way, as this is the single biggest place responsible for garbage creation in our app.

**Comment by ifesdjeen** [comment]
:+1: wow very nice find

**Comment by michaelklishin** [comment]
@ifesdjeen have you had a chance to look into this?

**Comment by ifesdjeen** [comment]
Already fixed locally

**Comment by michaelklishin** [comment]
@ifesdjeen when will your local fix land in this repo? In fact, with the Java DSL move, will this be relevant at all?

**Comment by ifesdjeen** [comment]
I've backported it a long time ago...
