### ISSUE TITLE
wrong type hint for clojurewerkz.cassaforte.uuids/unix-timestamp

### ISSUE THREAD

**Issue by Knotschi** [clojurewerkz/cassaforte#114]
using that function can sometimes lead to the Error Unable to resolve classname: clojure.core$long
(when I use it in the repl, it works fine, but I cant compile my project when I call that function)

I didn't really understood it but you can read it here:
http://dev.clojure.org/jira/browse/CLJ-1753
http://dev.clojure.org/jira/browse/CLJ-1674
https://github.com/jonase/eastwood#wrong-tag

somehow for clojure primitives the typehint should be after the function name 
(defn unix-timestamp ^long ...) instead of (defn ^long unix-timestamp ...)

**Comment by ifesdjeen** [comment]
fixed in 003586dde64034280bd1f96b876079946bde927e
