### ISSUE TITLE
:clustering-order behavior differs based on which version of clojure is used

### ISSUE THREAD

**Issue by gireeshramji** [clojurewerkz/cassaforte#117]
When running this query with my project level clojure dependency at 1.5.1, the table is created as expected:
``` clojure 
(cql/create-table 
   conn 
   "user" 
   {:userid :text, 
    :mode :text, 
    :time :text, 
    :pid :text, 
    :primary-key [[:userId :mode] :time :pid]} 
   (cquery/with {:clustering-order {:time :desc, :pid :asc}}) 
```

However if I change the clojure dependency to 1.6.0, the table fails to be created with the following error:

InvalidQueryException The order of columns in the CLUSTERING ORDER directive must be the one of the clustering key (time must appear before pid) com.datastax.driver.core.Responses$Error.asException (Responses.java:103)

**Comment by arr-ee** [comment]
Behaviour that you see is not dependent on Clojure version. Clojure maps do not preserve order — never had, never will — so using maps for order-dependent stuff is not advisable.

Replace `{:clustering-order {:time :desc, :pid :asc}}` with `{:clustering-order [[:time :desc] [:pid :asc]]}`, it should help.

**Comment by gireeshramji** [comment]
Thanks that worked. I knew it had to do with the non-order preservation of maps, but also thought that since it worked with 1.5.1 there might be an underlying issue.
Gireesh
