### ISSUE TITLE
Fails with a "org.clojure/tools.reader" after "0.9.2"

### ISSUE THREAD

**Issue by tolitius** [clojurewerkz/cassaforte#128]
could be something I am missing, and there is no official build for this yet, but...

## problem

Looks like anything that requires `org.clojure/tools.reader` greater than `0.9.2` will fail when combined with the latest (manual) build of `cassaforte`.

At first I thought it could be a `org.clojure/core.match` dependency, but it does not look like it:

```clojure
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [clojurewerkz/cassaforte "3.0.0-local" :exclusions [org.clojure/core.match]]
                 [org.clojure/core.async "0.2.385"]])
```

in this case `core.async` brings `org.clojure/tools.reader` "1.0.0-beta2" and this would fail:

```clojure
$ lein do clean, repl
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.8.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_20-b26

user=> (require '[clojure.core.async :as async])

CompilerException java.lang.ExceptionInInitializerError, compiling:(clojure/core/async/impl/ioc_macros.clj:1:1)
user=> *e

#error {
 :cause "Could not locate clojure/tools/reader/impl/ExceptionInfo__init.class or clojure/tools/reader/impl/ExceptionInfo.clj on classpath."
 :via ...
```

i.e. `clojure/tools/reader/impl/ExceptionInfo` was removed in `org.clojure/tools.reader` "0.10.0".

`clojurewerkz/cassaforte "3.0.0-local"` is `lein install` (no profile) from the master.

## observations

* _works_ if the `cassaforte` dependency is removed
* also works (the `require` part) if `tools.reader` is overridden:

```clojure
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [clojurewerkz/cassaforte "3.0.0-local"]
                 [org.clojure/core.async "0.2.385" :exclusions [org.clojure/tools.reader]]
                 [org.clojure/tools.reader "0.9.2"]])
```

but I am not sure what it'll break in `core.async`

**Comment by michaelklishin** [comment]
It's compilation of `clojure.core.async.impl.ioc_macros` that fails. Sorry but I don't consider problems like this to be those of Cassaforte. If you have a PR that resolves this, we'd be happy to consider it but library and version compatibility is not something we maintainers can do much about in general.

**Comment by michaelklishin** [comment]
Use `lein deps :tree` to see a tree of dependencies.

**Comment by tolitius** [comment]
yes, I did look at tree deps to extract this transitive `tools.reader` out of `org.clojure/tools.analyzer.jvm` that `core.async` depends on.

I would not treat this as a `cassaforte` problem, and I still don't, but since `tools.reader` is quite ubiquitous, not working with it diminishes `cassaforte` usability / adoption, so I wanted to bring this up before you guys do the build, since it could be something simple.
