### ISSUE TITLE
How do we get the bytes of a blob object?

### ISSUE THREAD

**Issue by socksy** [clojurewerkz/cassaforte#129]
Previously, in the bytes namespace (which was removed in commit e1abbf1dc3687248c2545e278a4dea848287dbfc) there was a `to-bytes` function. Now, only deserialize remains, being moved to the conversion namespace (in commit 148c2e9bea79cc02bc5746e85fd0240cb5c2ab21), afaict. I can put in the code previously doing the `to-bytes` function in my own namespace, ([using `.array` doesn't work in this instance](http://grokbase.com/t/cassandra/user/134brvqzd3/blobs-in-cql)), but it seems weird to me that this functionality was removed. What would be the best method?

**Comment by michaelklishin** [comment]
@ifesdjeen ping.

**Comment by ifesdjeen** [comment]
I've started typing but got distracted. Just check the type of it with `(type obj)` and address the signature in the documentation. I assume it's a `ByteBuffer` so converting it to bytes java equivalent would be:

```java
byte[] b = new byte[bb.remaining()]
bb.get(b);
```

Pretty much same in Clojure.

**Comment by michaelklishin** [comment]
`clojure.java.io` may have a nicer way of doing that.

**Comment by socksy** [comment]
Hang on, this didn't answer my question exactly, which is why this code was removed from the library :). The `.remaining()` `.get()` solution was previously in cassaforte, and now it's not. 

If I put bytes in a blob type, surely it should be natural that I should be able to get these bytes back out? IMO the Java-interop needed to get the data we put into Cassandra back out again should be in the Clojure wrapper around Cassandra :)

**Comment by michaelklishin** [comment]
there are existing Clojure libraries that operate byte buffers. I wouldn't mind bringing some of that stuff back but it's not necessarily essential.

**Comment by socksy** [comment]
I don't see any other Clojure libraries doing this thing in particular (e.g. I can't find somewhere in buffy or clojure.java.io that is addressing a resized backing array of a bytebuffer, nothing that is doing the java code extract above).

What's more, it's something that only happens because of a behaviour of Cassandra: 
- I take a ByteBuffer, put it into Cassandra's blob type using Cassaforte
- I get the value out using Cassaforte, and get a ByteBuffer
- but this is *not* the ByteBuffer I put in in the first place. 

I now have to do this ByteBuffer manipulation just to get the value out that I put in. And I have to do it with Java interop. I still see this is as the domain of the Clojure wrapper around Cassandra (and presumably, someone else did hence why it was there in the first place :)).

**Comment by michaelklishin** [comment]
Surely there [are NIO Clojure libraries](https://github.com/pjstadig/nio).

@ifesdjeen can you comment on *why* those functions were removed?

**Comment by ifesdjeen** [comment]
Ah, we used them internally, and had no more need for them, so they got removed. If they're useful for external usage, I do not mind having them back!

**Comment by ifesdjeen** [comment]
> but this is not the ByteBuffer I put in in the first place. 

Not sure what you're implying. You do not have to do it with java interop. It's just JVM classes so there's no other way rather than calling the class methods. I'm not sure what exactly you're trying to achieve: to get an array from byte buffer?

**Comment by socksy** [comment]
> Not sure what you're implying. You do not have to do it with java interop. It's just JVM classes so there's no other way rather than calling the class methods. 
Right, sorry, that's what I meant — ideally I would be able to do this without touching a Java class, since if I put in byte-array then it also should just work.
> I'm not sure what exactly you're trying to achieve: to get an array from byte buffer?
Yeah, eventually. I was using the ByteBuffer as the example because this behaviour was particularly perplexing to me.

But I think we're on the same page now. It's definitely useful behaviour, and it'd be nice to not have it in my own project's utilities NS since it does seem like obvious behaviour to have for the wrapper :)

**Comment by michaelklishin** [comment]
We are open to reinstalling some helpers in #130. Let's continue in a pull request ;)
