### ISSUE TITLE
Is support for Cassandra 3.X planned ?

### ISSUE THREAD

**Issue by lerouxrgd** [clojurewerkz/cassaforte#133]

**Comment by ifesdjeen** [comment]
Cassaforte is currently not actively maintained and kept up-to-date. I'm currently (also quite slowly) trying to help out @mpenet with [Alia](https://github.com/mpenet/alia), it has good support for 3.x and some features that would take a significant amount of time to get to Cassaforte. This time was already spent there.

**Comment by michaelklishin** [comment]
I still have some hopes to bring Cassaforte up-to-date. You can contribute, too, this is an open source projct.

**Comment by michaelklishin** [comment]
I'm closing this issue since this is a broad question and not a specific request that can be delivered.
